### ISSUE TITLE
خطا در شناسایی آی پی ایران

### ISSUE THREAD

**Issue by saeed3322** [0xNeu/GFIProxyProtector#1]
بعضی سایت ها مثل دو سایت زیر که سرورشون تو ایران هست بلاک نمیشن توسط این اسکریپت.

www.technolife.ir
gamefa.com

**Comment by 0xNeu** [comment]
وبسایت technolife.ir در حال حاضر بر روی شبکه هتزنر آلمان میزبانی میشه و در ایران نیست.
وبسایت gamefa.com در شبکه آسیاتک میزبانی میشه که در [پایگاه داده ی فعلی ](https://github.com/0xNeu/GFIGeoIP/blob/main/Aggregated_Data/agg_cidrs.csv) در ردیف 79.127.127.0/24,IR قرار داره، امکان داره شما از نسخه ی قدیمی اسکریپت پیش از [کامیت اصلاح رفرنس ها](https://github.com/0xNeu/GFIProxyProtector/commit/386922f0706d78e1970f3c3ea8def80a308a5f4a) استفاده کرده باشید. برای رفع مشکل یک بار همان اسکریپتی که clone کردید رو اجرا کنید و تمام گزینه ها رو غیرفعال کنید سپس  git pull کنید تا اخرین نسخه رو دریافت کنید و دوباره گزینه های مسدودسازی رو فعال کنید.

**Comment by 0xNeu** [comment]
> وقتی از داخل ایران پینگ کنید آی پی 185.166.104.4 زیر برمیگرده که توسط این اسکریپت بلاک نمیشه 

حق با شماست از ایران این آی‌پی برمیگرده که در پایگاه داده ها نبود و فقط برخی آی‌پی ها در اون زیرشبکه مسدود شده بودند! تغییراتی ایجاد کردم که هر شبکه لاقل در کلاس C فیلتر بشه یعنی تمام آی‌پی های 185.166.104.xxx لطفا یکبار git pull کنید تا اخرین نسخه رو دریافت کنید.

 رو یه سرور دیگه xray رو بالا آوردم و دوباره اسکریپت شما رو اجرا کردم ولی باز هم gamefa.com رو باز میکنه. با اینکه رنج آی پی تو iptable هست و باید بلاک بشه.

آیا سایر سرویس ها به درستی مسدود میشن و فقط این دو مورد مشکل دارند؟


> آیا مقدور هست براتون که گزینه ای به برنامه اضافه کنید که تمام دامین های IR فارغ از اینکه داخل ایران میزبانی میشن یا خارج بلاک بشه؟

بله ممکنه ولی نیاز به برنامه های دیگه دارید که یک DNS سرور محلی روی سرورتون راه‌اندازی کنید مثلا برنامه [blocky](https://github.com/0xERR0R/blocky) قادره این کار رو کنه. در [اسکریپت رنگین کمان](https://github.com/0xNeu/Rainbow) که پروکسی ها رو به همراه همه ی این امکانات نصب میکنه همین قابلیت وجود داره اما در حال کار روی نسخه ۳.۰ هستم و بهتره منتظر اون نسخه بمونید همین روزها نهایی میشه.

**Comment by 0xNeu** [comment]
> بله ممکنه ولی نیاز به برنامه های دیگه دارید که یک DNS سرور محلی روی سرورتون راه‌اندازی کنید مثلا برنامه [blocky](https://github.com/0xERR0R/blocky) قادره این کار رو کنه. در [اسکریپت رنگین کمان](https://github.com/0xNeu/Rainb0w) که پروکسی ها رو به همراه همه ی این امکانات نصب میکنه همین قابلیت وجود داره اما در حال کار روی نسخه ۳.۰ هستم و بهتره منتظر اون نسخه بمونید همین روزها نهایی میشه.

نسخه ۳.۰ اسکریپت Rainb0w هم اکنون در دسترسه و از این قابلیت برخورداره.
