### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by saeedpm** [0xNeu/GFIProxyProtector#2]
سلام 
من روی دبیان تست کردم ارور میده  وقتی از `iptables -A OUTPUT -m geoip --dst-cc IR,CN -j DROP ` استفاده میکنم
این خطارو میده `iptables v1.8.7 (nf_tables): Couldn't load match geoip':No such file or directory` 
هرچی هم برای رفع این مشکل نصب کردم باز فرقی نکرد

**Comment by 0xNeu** [comment]
سلام
برای نصب ماژول مدنظر حداقل یکبار باید یکی از گزینه های محافظتی رو فعال کنید (می تونید بعدش غرفعال کنید و از دستورات دستی خودتون مثل بالا استفاده کنید) ضمنا هم اسکریپت هم دستورات فوق رو با مجوز root اجرا کنید.
این اسکریپت با اخرین نسخه ی دبیان ۱۱ آزمایش شد و مشکلی نداشت.
