### ISSUE TITLE
استفاده از تانل

### ISSUE THREAD

**Issue by ali-frm** [0xNeu/GFIProxyProtector#4]
سلام وقت شما بخیر توسعه دهنده گرامی 
سوالی که دارم اینه که بعد از مسدود کردن اتصالات توسط این اسکریپت ایا ما میتونیم به سرور خودمون تانل بزنیم از سرور ایران ؟

**Comment by 0xNeu** [comment]
سلام وقت شما بخیر

شخصا سرور ایرانی ندارم که امتحان کنم اگر امتحان کردید و جواب گرفتید همینجا اطلاع رسانی کنید تا برای بقیه هم مکتوب بشه.

متشکر. پیروز باشید.

**Comment by Rezalxl** [comment]
سلام میتونید ایدی تلگرامتون بدید

**Comment by 0xNeu** [comment]
> سلام میتونید ایدی تلگرامتون بدید

سلام، خیر. از بخش Discussions همین مخزن استفاده کنید.
